version: "3.8"

services:
  nginx:
    image: challenge3-nginx
    build:
      context: ./docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - node-service

  node-service:
    image: challenge3-node-service
    build:
      context: ./docker/api
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      PORT: 3000
    depends_on:
      - db

  db:
    image: mariadb
    build:
      context: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"